### ISSUE TITLE
Versioning system

### ISSUE THREAD

**Issue by MattiSG** [ankane/setup-mongodb#2]
Hi @ankane and thank you for this action 👍

Having recently had to [deal with cross-platform MongoDB](https://github.com/orgs/community/discussions/30083) in GitHub Actions and following GitHub’s [decision](https://github.com/actions/runner-images/issues/5949) to default to having the service stopped in Windows (which you supposedly fixed after #1), the approach you take in this action seems the most relevant to me: using the preinstalled MongoDB servers instead of installing them or using Docker sounds much more efficient.

However, I am a bit confused by the versioning system used on this action. After you fixed #1, I see no version bump. Versioning is an important way to ensure consistency, and without it, I don't see us using this action as it is. Do you currently version this action? Do you have plans to do so? 🙂

**Comment by ankane** [comment]
Hey @MattiSG, thanks for the suggestion. I may adopt more traditional versioning in the future (which shouldn't affect the recommended usage of `ankane/setup-mongodb@v1`), but for now, the `v1` branch contains the latest changes, which will be bumped to `v2` for breaking changes.

**Comment by MattiSG** [comment]
Than you @ankane for your fast reply! I understand this means you do not intend to [publish this action](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) on the GitHub Marketplace, since versioning is a prerequisite. This would bring more visibility and contributors to this really useful action. Had I found it earlier, it could have saved me significant effort 😅

While we would prefer to contribute to this repo, considering this choice of yours and our need @OpenTermsArchive to abstract away from MongoDB setup cross-platform while maintaining reproducible history, we are considering forking this action and maintaining it with proper versioning and publishing. I wanted to check in with you before going further with that decision 🙂
