### ISSUE TITLE
Service does not start in Windows

### ISSUE THREAD

**Issue by MattiSG** [ankane/setup-mongodb#3]
The fix for #1 does not seem to work: in [this run](https://github.com/ambanum/OpenTermsArchive/runs/7970471938?check_suite_focus=true), the result is:

```log
sc config MongoDB start= auto
[SC] ChangeServiceConfig SUCCESS
sc start MongoDB
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.

child_process.js:674
    throw err;
    ^

Error: Command failed: sc start MongoDB
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at run (D:\a\_actions\ankane\setup-mongodb\v1\index.js:5:3)
    at Object.<anonymous> (D:\a\_actions\ankane\setup-mongodb\v1\index.js:36:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1053,
  signal: null,
  output: [ null, null, null ],
  pid: 7084,
  stdout: null,
  stderr: null
}
```

The original step is:

```yaml
      - uses: ankane/setup-mongodb@v1
        with:
          mongodb-version: 5.0
```

I noticed that Windows is not included in the [test matrix](https://github.com/ankane/setup-mongodb/blob/v1/.github/workflows/build.yml#L9) for this action, which prevented detecting this in CI.

**Comment by ankane** [comment]
Hey @MattiSG, are you seeing the same error on every run? `windows-2019` and `windows-2022` are both included in the [test matrix](https://github.com/ankane/setup-mongodb/blob/ce30d9041565cb469945895d5bde3384a254dd2e/.github/workflows/build.yml#L20-L23) and currently passing, so it may be an intermittent issue.

**Comment by MattiSG** [comment]
Thanks @ankane for your fast reply and for pointing out the tests!

> are you seeing the same error on every run?

I just [ran it](https://github.com/ambanum/OpenTermsArchive/actions/runs/2910553266) repeatedly, and indeed only that first attempt failed.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/222463/186377733-7622d025-302f-4e28-ac15-e898f82d7d1f.png">


> it may be an intermittent issue

Indeed, this flakiness unfortunately seems to be [systematic](https://github.com/actions/runner-images/issues/5949#issuecomment-1224200510) with that Windows service start. There does not seem to be a way to prevent this.

> both included in the [test matrix](https://github.com/ankane/setup-mongodb/blob/ce30d9041565cb469945895d5bde3384a254dd2e/.github/workflows/build.yml#L20-L23)

Sorry for that, I had not read further than the `os` matrix and had missed the `os` / `version` combination!
