### ISSUE TITLE
Install other versions for Windows

### ISSUE THREAD

**Issue by MattiSG** [ankane/setup-mongodb#4]
As an implementation note in case someone needs to have other versions available on Windows than the default 5.0, hopefully useful for some future contributor: it should be possible to install them with the preinstalled [Chocolatey](https://chocolatey.org) package manager with the following command:

```
run(`choco install mongodb --force --version=${mongoVersion}`)
```

The `--force` is needed to allow installing versions lower than the preinstalled one. `--allow-downgrade` is mentioned in the doc but did not seem necessary at the time of testing.

However, trying to execute this fails with the following error:

```
Installing mongodb.install...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\mongodb.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\mongodb.install\6.0.0\mongodb-windows-x86_64-6.0.0-signed.msi" ADDLOCAL="ServerService,Server,ProductFeature,Client,Router,MiscellaneousTools" /qn /norestart MONGO_DATA_PATH="C:\ProgramData\MongoDB\data\db"  MONGO_LOG_PATH="C:\ProgramData\MongoDB\log"  ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\mongodb.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of mongodb.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\mongodb.install\tools\chocolateyInstall.ps1'.
 See log for details.
```

You can see the failed run [here](https://github.com/MattiSG/setup-mongodb/actions/runs/2918224670) and variants with using `uninstall` or not [here](https://github.com/MattiSG/setup-mongodb/actions/runs/2918082398), [there](https://github.com/MattiSG/setup-mongodb/actions/runs/2918026397) and [there](https://github.com/MattiSG/setup-mongodb/actions/runs/2917962148).

The diff can be found [here](https://github.com/ankane/setup-mongodb/compare/v1...MattiSG:setup-mongodb:windows-versions?expand=1).

@ankane feel free to close this issue if you prefer to keep that issue count low, just wanted to share active knowledge now 😉

**Comment by ankane** [comment]
Hey @MattiSG, thanks for sharing! Would be nice to add if someone is able to get it fully working.
