### ISSUE TITLE
Action fails on Ubuntu 22 with `Unit mongod.service not found.`

### ISSUE THREAD

**Issue by MattiSG** [ankane/setup-mongodb#6]
Following the upgrade of GitHub runners in `ubuntu-latest` from Ubuntu 20.04 to version 22.04, builds fail with the following error:

```
sudo systemctl start mongod
Failed to start mongod.service: Unit mongod.service not found.
[…]
Error: Command failed: sudo systemctl start mongod
```

According to https://github.com/actions/runner-images/issues/6626, this is a consequence of MongoDB not being installed by default in Ubuntu anymore. GitHub Actions [stated](https://github.com/actions/runner-images/issues/6626#issuecomment-1327563345) it is a `wontfix` on their side.

A workaround is described in https://github.com/actions/runner-images/issues/6626#issuecomment-1327744126. The most recent suggestion in the MongoDB forum is https://www.mongodb.com/community/forums/t/installing-mongodb-over-ubuntu-22-04/159931/90 (all the rest seems very messy).

@ankane seems aware of the issue considering branch [`ubuntu-2204`](https://github.com/ankane/setup-mongodb/tree/ubuntu-2204) (with currently no viable fix).

@ankane we'll explore fixes on our own, but if you have a roadmap, an implementation path, or suggestions on this, it would be super useful to hear about it 😃

**Comment by ankane** [comment]
Hey @MattiSG, it looks like there's now a package for Ubuntu 22.04.

**Comment by MattiSG** [comment]
Thanks @ankane for your feedback! Unfortunately this [still fails](https://github.com/ambanum/OpenTermsArchive/actions/runs/3635327166/jobs/6134321688) with this action at version d89a18d69d3a1ea8dd766abebbb3c60ff33f5139 (see [code](https://github.com/ambanum/OpenTermsArchive/compare/ubuntu22)).

**Comment by ankane** [comment]
It looks like you're trying to use version 5.0, which isn't supported (only 6.0).

**Comment by ankane** [comment]
Just updated the default version, but you'll need to remove `mongodb-version: 5.0` in the workflow above.

**Comment by MattiSG** [comment]
Thanks @ankane for your clarification! We'll consider upgrading to Mongo 6 then 🙂

**Comment by MattiSG** [comment]
For future readers: in this version at least, this action [does not support](https://github.com/ambanum/OpenTermsArchive/actions/runs/3636434150/jobs/6136413727) Mongo 6 on Windows.
